language: node_js
notifications:
  email: false
node_js:
  - '7'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
